### ISSUE TITLE
ESP8266 port

### ISSUE THREAD

**Issue by h1aji** [DavidAntliff/esp32-i2c-lcd1602#2]
Is it possible to port this library for ESP8266?

**Comment by DavidAntliff** [comment]
Not trivially due to dependencies. If someone were to port my [esp32-smbus](https://github.com/DavidAntliff/esp32-smbus) component to ESP8266 then it would be much easier to port this one, but the smbus component is heavily dependent on the ESP-IDF which is only for the ESP32. An abstraction layer that separates the smbus protocol from the ESP-IDF implementation would be needed. It could definitely be done but I don't have time to do it myself - PRs are welcome.
